#Set the default layout for a post to the 'news' format
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"

#Number of pages in each archive page.
paginate: 6
paginate_path: "news/:num/"

gems: [jekyll-paginate]
rdiscount:
  extensions: [smart]
  
baseurl: "/publishmed"
production_url : http://anitapita.github.io.com/publishmed
BASE_PATH : http://anitapita.com/publishmed